swagger: "2.0"
info:
  description: "Dairy management"
  version: "1.0.0"
  title: "Dsuite api's"
  contact:
    email: "mkdeepan@gmail.com"
host: "localhost"
basePath: "/v2"
tags:
- name: "master"
  description: "All master datas in dairy management"
  externalDocs:
    description: "For testing"
    url: "http://localhost:8080/"
schemes:
- "http"
- "https"
paths:
  /getCustomerDetails/{cusId}:
    get:
      tags:
      - "master"
      summary: "Find customer by ID"
      description: "Returns a customer details"
      operationId: "getCustomerById"
      produces:      
      - "application/json"
      parameters:
      - name: "cusId"
        in: "path"
        description: "ID of customer"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Customer"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Customer not found"
      security:
      - api_key: []
  /getCustomerDetails:
    get:
      tags:
      - "master"
      summary: "Get all customers"
      description: "Returns a customer details"
      operationId: "getCustomers"
      produces:      
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CustomerList"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Customer not found"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Status:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  CustomerList:
    type: "object"
    properties:
      customers:
        type: "array"
        items:              
          $ref: '#/definitions/Customer'
      status:
        $ref: '#/definitions/Status'      
  Customer:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      customerName:
        type: "string"
      alias:
        type: "string"
      address:
        type: "string"
      route:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      contactNo:
        type: "integer"
        format: "int64"
      contactNo1:
        type: "integer"
        format: "int64"
      city:
        type: "string"
      pincode:
        type: "integer"
        format: "int32"
      customerType:
        type: "string"
      isActive:
        type: "integer"
        format: "int32"
        description: "User Status"
      isDelete:
        type: "integer"
        format: "int32"
        description: "User Status"
      createdBy:
        type: "string"
      createdAt:
        type: "string"
      updatedBy:
        type: "string"
      updatedAt:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"